{
 "title": "Thoth Kafka Consumers and Argo Workflows",
 "tags": [
  "thoth",
  "argo",
  "kafka",
  "smaug-prod"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_consumer",
    "query": "investigator-faust-web-thoth-infra-prod.apps.smaug.na.operate-first.cloud"
   },
   {
    "name": "instance_workflow_controller",
    "query": "workflow-controller-metrics-thoth-backend-prod.apps.smaug.na.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.smaug.na.operate-first.cloud"
   },
   {
    "name": "queue_name",
    "query": "cron_wf_queue,pod_queue,wf_cron_queue,workflow_queue"
   },
   { "name": "env", "query": "smaug-prod" },
   {
    "name": "instance_consumer_metrics",
    "query": "investigator-message-metrics-thoth-infra-prod.apps.smaug.na.operate-first.cloud"
   },
   {
    "name": "interval",
    "query": "1m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 7d"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Messages sent by producers",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "thoth_package_release_job_messages_sent_total{env=~\"$env\"}",
     "legendFormat": "{{env}} | {{message_type}} message sent from package releases producer ({{version}})"
    },
    {
     "expr": "thoth_graph_refresh_job_messages_sent_total{env=~\"$env\"}",
     "legendFormat": "{{env}} | {{message_type}} message sent from graph refresh producer ({{version}})"
    },
    {
     "expr": "thoth_kebechet_administrator_messages_sent_total{env=~\"$env\", prometheus=\"moc/smaug\"}",
     "legendFormat": "{{env}} | {{message_type}} message sent from kebechet administrator producer ({{version}})"
    },
    {
     "expr": "thoth_solver_messages_sent_total{env=~\"$env\", prometheus=\"moc/smaug\"}",
     "legendFormat": "{{env}} | {{message_type}} message sent from solver producer ({{version}})"
    }
   ]
  },
  {
   "title": "Kafka Messages processed by consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_investigator_processed_total{field=\"$instance_consumer\"}",
     "legendFormat": "{{message_type}} message Processed"
    }
   ]
  },
  {
   "title": "Kafka Messages In Progress in consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_investigator_in_progress{field=\"$instance_consumer\"}",
     "legendFormat": "{{message_type}} message In progress "
    }
   ]
  },
  {
   "title": "Kafka Messages Exceptions in consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_investigator_exceptions_total{field=\"$instance_consumer\"}",
     "legendFormat": "{{message_type}} message Exceptions"
    }
   ]
  },
  {
   "title": "Kafka Message consumption paused status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_investigator_halted_topics{field=\"$instance_consumer\"}",
     "legendFormat": "MESSAGE {{base_topic_name}} "
    }
   ]
  },
  {
   "title": "Kafka message encountered per version",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "message_count_by_version_total{field=\"$instance_consumer_metrics\", prometheus=\"moc/smaug\"}",
     "legendFormat": "MESSAGE {{message_type}} "
    }
   ]
  },
  {
   "title": "Workflows scheduled by consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_investigator_scheduled_workflows_total{field=\"$instance_consumer\"}"
    }
   ]
  },
  {
   "title": "Workflow status count",
   "type": "graph",
   "description": "A count of all workflows currently accessible by the controller by status",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{field='$instance_workflow_controller'}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(argo_workflows_count{field='$instance_workflow_controller'})",
     "legendFormat": "Total workflows"
    }
   ]
  },
  {
   "title": "Workflow queue latency [%]",
   "type": "graph",
   "description": "Percentage of workflows that has queue latency below a certain threshold",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_latency_bucket{field='$instance_workflow_controller', queue_name=\"$queue_name\"} / ignoring(le) group_left argo_workflows_queue_latency_count{field='$instance_workflow_controller', queue_name=\"$queue_name\"}",
     "legendFormat": "queue_latency: {{le}} | queue_name: {{$queue_name}}"
    }
   ]
  },
  {
   "title": "Argo workflows Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_status_counter{status=\"Error\"}",
     "legendFormat": "{{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Argo workflows Succeeded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_status_counter{status=\"Succeeded\"}",
     "legendFormat": "{{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Argo workflows Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_status_counter{status=\"Failed\"}",
     "legendFormat": "{{name}} : {{status}}"
    },
    {
     "expr": "increase(argo_workflows_status_counter{status=\"Failed\"}[$interval])",
     "legendFormat": "increase {{name}} : {{status}}"
    },
    {
     "expr": "rate(argo_workflows_status_counter{status=\"Failed\"}[$interval])",
     "legendFormat": "rate {{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Argo workflows Task Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_task_status_counter{status=\"Error\"}",
     "legendFormat": "{{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Argo workflows Task Succeeded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_task_status_counter{status=\"Succeeded\"}",
     "legendFormat": "{{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Argo workflows Task Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_task_status_counter{status=\"Failed\"}",
     "legendFormat": "{{name}} : {{status}}"
    },
    {
     "expr": "increase(argo_workflows_task_status_counter{status=\"Failed\"}[$interval])",
     "legendFormat": "Increase {{name}} : {{status}}"
    },
    {
     "expr": "rate(argo_workflows_task_status_counter{status=\"Failed\"}[$interval])",
     "legendFormat": "rate {{name}} : {{status}}"
    }
   ]
  }
 ]
}