---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: adviser
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: prescriptions
spec:
  lookupPolicy:
    local: true
