---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: triage-party
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      from:
        kind: ImageStreamTag
        name: v1.4.0
      name: latest
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/thoth-station/triage-party:v1.4.0
      importPolicy: {}
      name: v1.4.0
      referencePolicy:
        type: Local
