---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: triage-party
  name: triage-party-pcache
spec:
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
