apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thoth-station-prow-monitor
  labels:
    monitor-component: thoth-station
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: https
  namespaceSelector:
    matchNames:
      - opf-ci-prow
  selector: {}
