{
 "title": "Thoth SLI/SLO",
 "tags": [
  "SLO",
  "SLI",
  "Thoth"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.balrog.aws.operate-first.cloud"
   },
   {
    "name": "instance_metrics",
    "query": "metrics-exporter-thoth-infra-prod.apps.balrog.aws.operate-first.cloud"
   },
   { "name": "env", "query": "balrog-prod" }
  ]
 },
 "panels": [
  {
   "title": "APIs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{field=\"user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "User API"
    },
    {
     "expr": "up{field=\"management-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Management API"
    }
   ]
  },
  {
   "title": "GitHub App",
   "type": "stat",
   "description": "Considering thoth adviser manager working ",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{field=\"user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"} == 1 and on(prometheus) up{field=\"investigator-faust-web-thoth-infra-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"} == 1 and on(prometheus) up{field=\"workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"} and on(prometheus) thoth_openshift_connection_issues{prometheus=\"aws/balrog\"} and on(prometheus) thoth_graphdb_connection_issues{prometheus=\"aws/balrog\"} and on(prometheus) thoth_kafka_connection_issues{prometheus=\"aws/balrog\"} and on(prometheus) thoth_ceph_connection_issues{prometheus=\"aws/balrog\"}",
     "legendFormat": "User API"
    }
   ]
  },
  {
   "title": "Components",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{field=\"investigator-faust-web-thoth-infra-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Investigator"
    },
    {
     "expr": "up{field=\"investigator-message-metrics-thoth-infra-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Investigator metrics"
    },
    {
     "expr": "up{field=\"metrics-exporter-thoth-infra-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Metrics exporter"
    },
    {
     "expr": "up{field=\"postgres-metrics-exporter-thoth-graph-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "PostgreSQL Metrics"
    }
   ]
  },
  {
   "title": "Workflow Controller ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{field=\"workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "thoth-backend-prod"
    },
    {
     "expr": "up{field=\"workflow-controller-metrics-thoth-middletier-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "thoth-middletier-prod"
    },
    {
     "expr": "up{field=\"workflow-controller-metrics-thoth-amun-inspection-prod.apps.balrog.aws.operate-first.cloud\", prometheus=\"aws/balrog\"}",
     "legendFormat": "thoth-amun-inspection-prod"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_openshift_connection_issues{prometheus=\"aws/balrog\"}",
     "legendFormat": "OpenShift"
    },
    {
     "expr": "thoth_graphdb_connection_issues{prometheus=\"aws/balrog\"}",
     "legendFormat": "PostgreSQL"
    },
    {
     "expr": "thoth_kafka_connection_issues{prometheus=\"aws/balrog\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "thoth_ceph_connection_issues{prometheus=\"aws/balrog\"}",
     "legendFormat": "Ceph"
    }
   ]
  },
  {
   "title": "Learning Rate Solver Python Packages",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[$interval])",
     "legendFormat": "Thoth Solver Learning rate SLI (increase) | instance: {{instance}} | {{job}}"
    }
   ]
  },
  {
   "title": "Learning Rate and Estimated time to solve all packages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[$interval])",
     "legendFormat": "Thoth Unsolved Learning rate SLI (increase)"
    },
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages{field=\"$instance_metrics\"} / increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))",
     "legendFormat": "Estimated hours to solve all unsolved packages (1h inverval)"
    },
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages{field=\"$instance_metrics\"} / increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days to solve all unsolved packages (1h inverval)"
    },
    {
     "expr": "(thoth_graphdb_number_python_package_versions{field=\"$instance_metrics\"} / increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days to solve all packages adding a new solver (1h interval)"
    }
   ]
  },
  {
   "title": "Unsolved Python Packages,",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_unsolved_python_packages{field=\"$instance_metrics\"}",
     "legendFormat": "Thoth Number of unsolved packages"
    }
   ]
  },
  {
   "title": "Estimated time to solve packages per solver [days]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages_per_solver{field=\"$instance_metrics\"}  / ignoring(solver_name) group_left increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days to solve (1h inverval): {{solver_name}}"
    }
   ]
  },
  {
   "title": "Estimated time to solve packages per solver [hours]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages_per_solver{field=\"$instance_metrics\"}  / ignoring(solver_name) group_left increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))",
     "legendFormat": "Estimated hours to solve (1h inverval): {{solver_name}}"
    }
   ]
  },
  {
   "title": "Estimated days to solve all packages adding a new solver (current learning rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thoth_graphdb_number_python_package_versions{field=\"$instance_metrics\"} / increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days (1h interval)"
    }
   ]
  },
  {
   "title": "Estimated days to solve all unsolved packages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages{field=\"$instance_metrics\"} / increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days (1h interval)"
    }
   ]
  },
  {
   "title": "Estimated days to solve all packages for solver-rhel-8-py38",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages_per_solver{field=\"$instance_metrics\", solver_name=\"solver-rhel-8-py38\"}  / ignoring(solver_name) group_left increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days (1h interval)"
    }
   ]
  },
  {
   "title": "Estimated days to solve all packages for solver-fedora-34-py39",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(thoth_graphdb_total_number_unsolved_python_packages_per_solver{field=\"$instance_metrics\", solver_name=\"solver-fedora-34-py39\"}  / ignoring(solver_name) group_left increase(thoth_graphdb_unsolved_python_package_versions_change_total{field=\"$instance_metrics\"}[1h]))/24",
     "legendFormat": "Estimated days (1h interval)"
    }
   ]
  },
  {
   "title": "SI unanalyzed Python Packages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_unanalyzed_python_packages{field=\"$instance_metrics\"}",
     "legendFormat": "Thoth Number of SI unanalyzed packages"
    },
    {
     "expr": "increase(thoth_graphdb_si_unanalyzed_python_package_versions_change_total{field=\"$instance_metrics\"}[$interval])",
     "legendFormat": "Thoth SI Learning rate SLI (increase)"
    }
   ]
  },
  {
   "title": "Rate Workflow status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(argo_workflows_status_counter{field=\"$instance\"}[$interval])",
     "legendFormat": "increase {{name}} : {{status}}"
    }
   ]
  },
  {
   "title": "Solver Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows error"
    }
   ]
  },
  {
   "title": "Solver Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}) / (sum(thoth_sli_weekly{metric_name=\"solver_workflows_succeeded\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_failed\", sli_type=\"component_quality\"}) + sum(thoth_sli_weekly{metric_name=\"solver_workflows_error\", sli_type=\"component_quality\"}))",
     "legendFormat": "% solver workflows error"
    }
   ]
  },
  {
   "title": "Adviser Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_succeeded\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflows_failed\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflows_error\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows error"
    }
   ]
  },
  {
   "title": "Adviser Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_succeeded\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflows_failed\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflows_error\", sli_type=\"component_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflows_.*\", sli_type=\"component_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows error"
    }
   ]
  },
  {
   "title": "Adviser Workflow Task quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_succeeded\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflow_tasks_failed\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflow_tasks_error\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task error"
    }
   ]
  },
  {
   "title": "Adviser Workflow Task quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_succeeded\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflow_tasks_failed\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"adviser_workflow_tasks_error\", sli_type=\"workflow_task_quality\", env=\"$env\"}) / sum(thoth_sli_weekly{metric_name=~\"adviser_workflow_tasks_.*\", sli_type=\"workflow_task_quality\", env=\"$env\"})",
     "legendFormat": "% adviser workflows task error"
    }
   ]
  },
  {
   "title": "Security Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"security_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"security_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"security_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows error"
    }
   ]
  },
  {
   "title": "Security Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"security_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"security_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"security_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"security_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% security workflows error"
    }
   ]
  },
  {
   "title": "Kebechet Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"kebechet_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"kebechet_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows error"
    }
   ]
  },
  {
   "title": "Kebechet Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"kebechet_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"kebechet_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"kebechet_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% kebechet workflows error"
    }
   ]
  },
  {
   "title": "Provenance Checker Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"provenance_checker_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"provenance_checker_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows error"
    }
   ]
  },
  {
   "title": "Provenance Checker Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"provenance_checker_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"provenance_checker_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"provenance_checker_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% provenance checker workflows error"
    }
   ]
  },
  {
   "title": "Package Extract Workflow quality",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"package_extract_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"package_extract_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows error"
    }
   ]
  },
  {
   "title": "Package Extract Workflow quality",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_succeeded\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows succeeded"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"package_extract_workflows_failed\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows failed"
    },
    {
     "expr": "sum(thoth_sli_weekly{metric_name=\"package_extract_workflows_error\", sli_type=\"component_quality\"}) / sum(thoth_sli_weekly{metric_name=~\"package_extract_workflows_.*\", sli_type=\"component_quality\"})",
     "legendFormat": "% package extract workflows error"
    }
   ]
  },
  {
   "title": "Solver Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Solver Workflow Task latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Adviser Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 11, "x": 1, "y": 116 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Adviser Workflow Task latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"solver_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"adviser_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Security Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"security_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Kebechet Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Provenance Checker Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly_stage{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly_stage{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"provenance_checker_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Revsolver Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 131 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"revsolver_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Kebechet Administrator Workflow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_latency\", metric_name=\"kebechet_administrator_workflows_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Package Extract Workflow Task latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
   "targets": [
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_5\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 5s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_10\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 10s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_30\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 30s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_60\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 60s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_120\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 120s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_180\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 180s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_300\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 300s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_600\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 600s"
    },
    {
     "expr": "sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_900\"}) / sum(thoth_sli_weekly{sli_type=\"component_task_latency\", metric_name=\"package_extract_workflows_task_latency_bucket_+Inf\"})",
     "legendFormat": "< 900s"
    }
   ]
  },
  {
   "title": "Adviser Statistics",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_reporter_success_adviser_gauge{env=\"$env\"}",
     "legendFormat": "Successfull adviser runs {{adviser_version}}"
    },
    {
     "expr": "thoth_reporter_failed_adviser_gauge{env=\"$env\"}",
     "legendFormat": "Failed adviser runs {{adviser_version}}"
    }
   ]
  },
  {
   "title": "Adviser Statistics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 139 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "thoth_reporter_success_adviser_gauge{env=\"$env\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Successfull adviser runs {{adviser_version}}"
    },
    {
     "expr": "thoth_reporter_failed_adviser_gauge{env=\"$env\", prometheus=\"aws/balrog\"}",
     "legendFormat": "Failed adviser runs {{adviser_version}}"
    }
   ]
  },
  {
   "title": "Adviser Failures Analysis",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "thoth_reporter_failed_adviser_justifications_gauge{env=\"$env\", prometheus=\"aws/balrog\"}",
     "legendFormat": "adviser {{adviser_version}} failures % due to {{justification}}"
    }
   ]
  },
  {
   "title": "Number of requests vs number of documents created on Ceph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_reporter_requests_gauge{env=\"$env\"} - thoth_reporter_reports_gauge{env=\"$env\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Number of requests and documents created on Ceph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_reporter_requests_gauge{env=\"$env\"}",
     "legendFormat": "requests for {{component}}"
    },
    {
     "expr": "thoth_reporter_reports_gauge{env=\"$env\"}",
     "legendFormat": "reports for {{component}}"
    }
   ]
  }
 ]
}