apiVersion: batch/v1
kind: Job
metadata:
  name: peribolos
spec:
  backoffLimit: 2
  template:
    metadata:
      name: peribolos
    spec:
      containers:
        - name: peribolos
          image: gcr.io/k8s-prow/peribolos:latest
          args:
            - --config-path=/etc/config/org_thoth-station.yaml
            - --github-token-path=/etc/github/oauth
            - --min-admins=2
            - --maximum-removal-delta=0.15
            - --require-self=true
            - --fix-org
            - --fix-org-members
            - --fix-repos
            - --fix-teams
            - --fix-team-members
            - --fix-team-repos
            - --allow-repo-archival
            - --confirm
          volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: oauth
          secret:
            secretName: oauth-token
        - name: config
          configMap:
            name: peribolos-thoth-station
